version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_HOST: mongodb://mongo:27017/
      MONGODB_NAME: ISBN-BOOK-mongo
      PRIVATE_KEY:  your_jwt_secret_here
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    container_name: ISBN-BOOK-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mongo-data:
  redis_data: